
services:
  codewave-client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: codewave-client
    image: codewave-client:v1.0
    restart: unless-stopped
    environment:
      - NODE_ENV=${NODE_ENV:-produccion}
    ports:
      - "3000:80"
    networks:
      - internal

  codewave-api:
    build:
      context: .
      dockerfile: Dockerfile.server 
    container_name: codewave-api
    image: codewave-api:v1.0
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV:-produccion}
      - API_PORT=${API_PORT:-5000}
    restart: unless-stopped
    networks:
      - internal

networks:
  internal:
    driver: bridge
  
