
services:
  codewave-client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: codewave-client
    restart: unless-stopped
    volumes:
      - /var/www/html/codewave:/dist
      #- vite-dist:/dist
    environment:
      - VITE_API_BASE_URl=http://localhost:8089
    command: ["true"] 
    networks:
      internal:
        ipv4_address: 172.18.0.20

  codewave-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: codewave-server
    restart: always
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - API_PORT=5010
    depends_on:
      - codewave-client
    networks:
      internal:
        ipv4_address: 172.18.0.10
    
  nginx:
    image: nginx:alpine
    container_name: codewave-nginx
    restart: always
    ports:
      - "8089:80"
    volumes:
      - /var/www/html/codewave:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
  vite-dist:

networks:
  internal:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
  
