# Etapa 1: Construcción
FROM node:20-alpine AS builder

ENV DIR=/app

WORKDIR $DIR

RUN apk update && apk add --no-cache dumb-init

COPY package.json pnpm-lock.yaml* ./

RUN npm install -g pnpm && pnpm install --frozen-lockfile

COPY . . 

RUN pnpm run build:server

# Etapa 2: Ejecución
FROM node:20-alpine

WORKDIR /app

# Copia solo los archivos necesarios desde la etapa de construcción
COPY --from=builder /usr/bin/dumb-init /usr/bin/dumb-init
COPY --from=builder /app/dist/server ./dist/server
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/pnpm-lock.yaml ./pnpm-lock.yaml

# Instala solo las dependencias de producción
RUN npm install -g pnpm && pnpm install --frozen-lockfile --prod

EXPOSE $API_PORT

CMD ["dumb-init","node", "dist/server/index.js"]