
services:
  codewave-client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: codewave-client
    restart: always
    volumes:
      - vite-dist:/dist
    environment:
      - VITE_API_BASE_URl=http://localhost:8089
    networks:
      internal:
        ipv4_address: 172.18.0.20

  codewave-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: codewave-server
    restart: always
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - API_PORT=5010
    depends_on:
      - codewave-client
    networks:
      internal:
        ipv4_address: 172.18.0.10

  nginx:
    image: nginx:alpine
    container_name: vite-nginx
    ports:
      - "8089:80"
    volumes:
      - vite-dist:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - codewave-client
      - codewave-server
    networks:
      - internal

volumes:
  vite-dist:

networks:
  internal:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
  
