FROM node:20-alpine AS builder

WORKDIR /app

RUN apk update && apk add --no-cache dumb-init

COPY package.json pnpm-lock.yaml* ./
RUN --mount=type=cache,target=/root/.pnpm-store npm install -g pnpm && pnpm install --frozen-lockfile

COPY . .
RUN pnpm run build:server

COPY ./src/api/mail/templetes/ ./dist/api/mail/templates/

# Etapa 2: Ejecución
FROM node:20-alpine

WORKDIR /app

COPY --from=builder /usr/bin/dumb-init /usr/bin/dumb-init
COPY --from=builder /app/dist/api ./dist/api
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/pnpm-lock.yaml ./pnpm-lock.yaml

RUN --mount=type=cache,target=/root/.pnpm-store npm install -g pnpm && pnpm install --frozen-lockfile --prod

EXPOSE $API_PORT

CMD ["dumb-init", "node", "dist/api/index.js"]