# Etapa 1: Construcción
FROM node:20-alpine AS builder

WORKDIR /app

COPY package.json pnpm-lock.yaml* ./

RUN npm install -g pnpm && pnpm install --frozen-lockfile

COPY . .

RUN pnpm run build:server

# Etapa 2: Ejecución
FROM node:20-alpine

WORKDIR /app

# Copia solo los archivos necesarios desde la etapa de construcción
COPY --from=builder /app/dist/server ./dist/server
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/pnpm-lock.yaml ./pnpm-lock.yaml

# Instala solo las dependencias de producción
RUN npm install -g pnpm && pnpm install --frozen-lockfile --prod

EXPOSE 3000

CMD ["node", "dist/server/mailServer.js"]