
services:
  codewave-client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: codewave-client
    volumes:
      - vite-dist:/dist
    command: ["true"]  # Para que el contenedor no se quede ejecutando
    networks:
      - internal-network

  codewave-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: codewave-server
    env_file:
      - .env
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - codewave-client
    networks:
      - internal-network

  nginx:
    image: nginx:alpine
    container_name: vite-nginx
    ports:
      - "8089:80"
    volumes:
      - vite-dist:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - codewave-client

volumes:
  vite-dist:

networks:
  internal-network:
    driver: bridge
  
