
services:
  codewave-client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: codewave-client
    volumes:
      - vite-dist:/dist
    environment:
      - VITE_API_BASE_URL=http://localhost:8089
    command: ["true"]  
    networks:
      - internal

  codewave-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: codewave-server
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - API_PORT=5010
    depends_on:
      - codewave-client
    networks:
      - internal

  nginx:
    image: nginx:alpine
    container_name: vite-nginx
    ports:
      - "8089:80"
    volumes:
      - vite-dist:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - codewave-client
      - codewave-server
    networks:
      - internal

volumes:
  vite-dist:

networks:
  internal:
    driver: bridge
  
