
services:
  codewave-client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: codewave-client
    volumes:
      - vite-dist:/dist
    command: ["true"]  # Para que el contenedor no se quede ejecutando

  codewave-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: codewave-server
    ports:
      - "3000:3000"
    depends_on:
      - codewave-client

  nginx:
    image: nginx:alpine
    container_name: vite-nginx
    ports:
      - "8089:80"
    volumes:
      - vite-dist:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - codewave-client

volumes:
  vite-dist:
