version: "3.8"

services:
  vite-build:
    build: .
    container_name: vite-builder
    volumes:
      - vite-dist:/dist
    command: ["true"]  # Para que el contenedor no se quede ejecutando

  nginx:
    image: nginx:alpine
    container_name: vite-nginx
    ports:
      - "8089:80"
    volumes:
      - vite-dist:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - vite-build

volumes:
  vite-dist:
